name: codacy-coverage-reporter

on:
  push:
    branches:
      - main

jobs:
  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    name: codacy-coverage-reporter
    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@main
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/clover.xml